# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logsage < Formula
  desc "AI-powered log analysis CLI that identifies root causes of system failures"
  homepage "https://github.com/UreaLaden/log-sage"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UreaLaden/log-sage/releases/download/v1.1.0/logsage_1.1.0_darwin_amd64.tar.gz"
      sha256 "4fea62b069b3a23fd94cccc3be01bcfdbec3dc71ea77da2403b96601e7b378ba"

      define_method(:install) do
        bin.install "logsage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UreaLaden/log-sage/releases/download/v1.1.0/logsage_1.1.0_darwin_arm64.tar.gz"
      sha256 "6e5215c94622d57843a0539d95b63e1823d23f2ff8bffb6d5ef8d8cfc649e44c"

      define_method(:install) do
        bin.install "logsage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/UreaLaden/log-sage/releases/download/v1.1.0/logsage_1.1.0_linux_amd64.tar.gz"
      sha256 "cb10bc6d42eb7d6feae970a3f3cfcf41c55ce9cd7926d694d268d4da57f9e181"
      define_method(:install) do
        bin.install "logsage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/UreaLaden/log-sage/releases/download/v1.1.0/logsage_1.1.0_linux_arm64.tar.gz"
      sha256 "2bae3c457cbc6499f2f9b6f6550c1a5ff0ba7e76425853f855618a06d2c2038d"
      define_method(:install) do
        bin.install "logsage"
      end
    end
  end

  test do
    system "#{bin}/logsage version"
  end
end
