# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logsage < Formula
  desc "AI-powered log analysis CLI that identifies root causes of system failures"
  homepage "https://github.com/UreaLaden/log-sage"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UreaLaden/log-sage/releases/download/v1.1.1/logsage_1.1.1_darwin_amd64.tar.gz"
      sha256 "4afe4ae8766574a9564664e5bf0d32c5c2f7f2a0f808e0a5766234eed36c8087"

      define_method(:install) do
        bin.install "logsage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UreaLaden/log-sage/releases/download/v1.1.1/logsage_1.1.1_darwin_arm64.tar.gz"
      sha256 "0c0de1c1156da31bd6f6f34bd5fdfe3b024d1fe02e1ff9c6f7ff864f1dcc53e1"

      define_method(:install) do
        bin.install "logsage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/UreaLaden/log-sage/releases/download/v1.1.1/logsage_1.1.1_linux_amd64.tar.gz"
      sha256 "36f3751546eb2586c3d9db4529458a182042378c46daf659e5d4ca810d69b5c4"
      define_method(:install) do
        bin.install "logsage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/UreaLaden/log-sage/releases/download/v1.1.1/logsage_1.1.1_linux_arm64.tar.gz"
      sha256 "d45294aebf424a4d8f22e4aa0090eb0f95df60e3b81a0b93ad3b5dff75c07779"
      define_method(:install) do
        bin.install "logsage"
      end
    end
  end

  test do
    system "#{bin}/logsage version"
  end
end
